import type { CardDef } from '../types';

// Helper to keep definitions terse but explicit.
const C = (c: CardDef): CardDef => c;

// ============================================================
// VUKODLAK — warrior built around BIJES (rage) build/spend
// ============================================================
const VUKODLAK: CardDef[] = [
  // --- starters ---
  C({
    id: 'ugriz',
    name: 'Ugriz',
    type: 'napad',
    rarity: 'osnovna',
    cls: 'vukodlak',
    cost: 1,
    target: 'enemy',
    text: 'Nanesi 6 štete.',
    upgradedText: 'Nanesi 9 štete.',
    actions: [{ kind: 'damage', amount: 6 }],
    upgradedActions: [{ kind: 'damage', amount: 9 }],
    flavor: 'Prvi ujed uvijek je najdublji.',
  }),
  C({
    id: 'krzno',
    name: 'Krzno',
    type: 'vjestina',
    rarity: 'osnovna',
    cls: 'vukodlak',
    cost: 1,
    target: 'self',
    text: 'Stekni 5 štita.',
    upgradedText: 'Stekni 8 štita.',
    actions: [{ kind: 'block', amount: 5 }],
    upgradedActions: [{ kind: 'block', amount: 8 }],
    flavor: 'Gusto krzno trpi i mraz i sječivo.',
  }),
  C({
    id: 'razjari',
    name: 'Razjari',
    type: 'napad',
    rarity: 'osnovna',
    cls: 'vukodlak',
    cost: 2,
    target: 'enemy',
    text: 'Nanesi 8 štete. Daj 2 Ranjivosti. Stekni 1 Bijes.',
    upgradedText: 'Nanesi 11 štete. Daj 3 Ranjivosti. Stekni 1 Bijes.',
    actions: [
      { kind: 'damage', amount: 8 },
      { kind: 'status', status: 'vulnerable', amount: 2 },
      { kind: 'gainBjes', amount: 1 },
    ],
    upgradedActions: [
      { kind: 'damage', amount: 11 },
      { kind: 'status', status: 'vulnerable', amount: 3 },
      { kind: 'gainBjes', amount: 1 },
    ],
  }),

  // --- common ---
  C({
    id: 'zamah',
    name: 'Zamah',
    type: 'napad',
    rarity: 'cesta',
    cls: 'vukodlak',
    cost: 1,
    target: 'enemy',
    text: 'Nanesi 4 štete dvaput.',
    upgradedText: 'Nanesi 5 štete dvaput.',
    actions: [{ kind: 'damage', amount: 4, hits: 2 }],
    upgradedActions: [{ kind: 'damage', amount: 5, hits: 2 }],
  }),
  C({
    id: 'nalet',
    name: 'Nalet',
    type: 'napad',
    rarity: 'cesta',
    cls: 'vukodlak',
    cost: 1,
    target: 'enemy',
    text: 'Nanesi 7 štete. Stekni 1 Bijes.',
    upgradedText: 'Nanesi 10 štete. Stekni 2 Bijesa.',
    actions: [
      { kind: 'damage', amount: 7 },
      { kind: 'gainBjes', amount: 1 },
    ],
    upgradedActions: [
      { kind: 'damage', amount: 10 },
      { kind: 'gainBjes', amount: 2 },
    ],
  }),
  C({
    id: 'stit_kostiju',
    name: 'Štit od kostiju',
    type: 'vjestina',
    rarity: 'cesta',
    cls: 'vukodlak',
    cost: 1,
    target: 'self',
    text: 'Stekni 8 štita. Stekni 1 Bijes.',
    upgradedText: 'Stekni 11 štita. Stekni 1 Bijes.',
    actions: [
      { kind: 'block', amount: 8 },
      { kind: 'gainBjes', amount: 1 },
    ],
    upgradedActions: [
      { kind: 'block', amount: 11 },
      { kind: 'gainBjes', amount: 1 },
    ],
  }),
  C({
    id: 'urlik',
    name: 'Urlik',
    type: 'vjestina',
    rarity: 'cesta',
    cls: 'vukodlak',
    cost: 1,
    target: 'all-enemies',
    text: 'Svim neprijateljima daj 2 Nemoći.',
    upgradedText: 'Svim neprijateljima daj 2 Nemoći i 1 Ranjivost.',
    actions: [{ kind: 'statusAll', status: 'weak', amount: 2 }],
    upgradedActions: [
      { kind: 'statusAll', status: 'weak', amount: 2 },
      { kind: 'statusAll', status: 'vulnerable', amount: 1 },
    ],
    flavor: 'Krv im se ledi prije nego što kandže stignu.',
  }),
  C({
    id: 'krvozednost',
    name: 'Krvožednost',
    type: 'napad',
    rarity: 'cesta',
    cls: 'vukodlak',
    cost: 1,
    target: 'enemy',
    text: 'Nanesi 8 štete. Ako je meta ispod 40% zdravlja, nanesi još 6.',
    upgradedText: 'Nanesi 11 štete. Ako je meta ispod 40% zdravlja, nanesi još 8.',
    actions: [],
    onPlay: ({ api, state, targetIndex, upgraded }) => {
      const base = upgraded ? 11 : 8;
      const bonus = upgraded ? 8 : 6;
      const tgt =
        targetIndex !== null && state.enemies[targetIndex]?.hp > 0
          ? state.enemies[targetIndex]
          : state.enemies.find((e) => e.hp > 0) ?? null;
      let dmg = base;
      if (tgt && tgt.hp <= tgt.maxHp * 0.4) dmg += bonus;
      api.attack(dmg, targetIndex);
    },
  }),
  C({
    id: 'pomama',
    name: 'Pomama',
    type: 'vjestina',
    rarity: 'cesta',
    cls: 'vukodlak',
    cost: 0,
    target: 'self',
    text: 'Stekni 2 Bijesa. Izvuci 1 kartu.',
    upgradedText: 'Stekni 3 Bijesa. Izvuci 1 kartu.',
    actions: [
      { kind: 'gainBjes', amount: 2 },
      { kind: 'draw', amount: 1 },
    ],
    upgradedActions: [
      { kind: 'gainBjes', amount: 3 },
      { kind: 'draw', amount: 1 },
    ],
  }),
  C({
    id: 'zubi_kandze',
    name: 'Zubi i kandže',
    type: 'napad',
    rarity: 'cesta',
    cls: 'vukodlak',
    cost: 1,
    target: 'enemy',
    text: 'Nanesi štetu jednaku 4 + tvoj Bijes.',
    upgradedText: 'Nanesi štetu jednaku 6 + tvoj Bijes.',
    actions: [],
    keywords: ['Pojačano bijesom'],
    onPlay: ({ api, targetIndex, upgraded }) => {
      api.attack((upgraded ? 6 : 4) + api.bjes(), targetIndex);
    },
  }),
  C({
    id: 'tvrda_koza',
    name: 'Tvrda koža',
    type: 'vjestina',
    rarity: 'cesta',
    cls: 'vukodlak',
    cost: 1,
    target: 'self',
    text: 'Stekni 6 štita. Stekni 2 Oklopa.',
    upgradedText: 'Stekni 8 štita. Stekni 3 Oklopa.',
    actions: [
      { kind: 'block', amount: 6 },
      { kind: 'selfStatus', status: 'metal', amount: 2 },
    ],
    upgradedActions: [
      { kind: 'block', amount: 8 },
      { kind: 'selfStatus', status: 'metal', amount: 3 },
    ],
    keywords: ['Oklop'],
  }),
  C({
    id: 'pokolj',
    name: 'Pokolj',
    type: 'napad',
    rarity: 'cesta',
    cls: 'vukodlak',
    cost: 2,
    target: 'enemy',
    text: 'Nanesi 15 štete.',
    upgradedText: 'Nanesi 20 štete.',
    actions: [{ kind: 'damage', amount: 15 }],
    upgradedActions: [{ kind: 'damage', amount: 20 }],
  }),
  C({
    id: 'zavijanje',
    name: 'Zavijanje',
    type: 'vjestina',
    rarity: 'cesta',
    cls: 'vukodlak',
    cost: 1,
    target: 'self',
    text: 'Stekni 3 Bijesa. Izgubi 2 zdravlja.',
    upgradedText: 'Stekni 4 Bijesa. Izgubi 2 zdravlja.',
    actions: [
      { kind: 'gainBjes', amount: 3 },
      { kind: 'loseHp', amount: 2 },
    ],
    upgradedActions: [
      { kind: 'gainBjes', amount: 4 },
      { kind: 'loseHp', amount: 2 },
    ],
  }),
  C({
    id: 'trzaj',
    name: 'Trzaj',
    type: 'napad',
    rarity: 'cesta',
    cls: 'vukodlak',
    cost: 0,
    target: 'enemy',
    text: 'Nanesi 3 štete. Izvuci 1 kartu.',
    upgradedText: 'Nanesi 5 štete. Izvuci 1 kartu.',
    actions: [
      { kind: 'damage', amount: 3 },
      { kind: 'draw', amount: 1 },
    ],
    upgradedActions: [
      { kind: 'damage', amount: 5 },
      { kind: 'draw', amount: 1 },
    ],
  }),
  C({
    id: 'razderotina',
    name: 'Razderotina',
    type: 'napad',
    rarity: 'cesta',
    cls: 'vukodlak',
    cost: 1,
    target: 'enemy',
    text: 'Nanesi 6 štete. Daj 2 Ranjivosti.',
    upgradedText: 'Nanesi 8 štete. Daj 3 Ranjivosti.',
    actions: [
      { kind: 'damage', amount: 6 },
      { kind: 'status', status: 'vulnerable', amount: 2 },
    ],
    upgradedActions: [
      { kind: 'damage', amount: 8 },
      { kind: 'status', status: 'vulnerable', amount: 3 },
    ],
  }),
  C({
    id: 'okrilje_noci',
    name: 'Okrilje noći',
    type: 'vjestina',
    rarity: 'cesta',
    cls: 'vukodlak',
    cost: 2,
    target: 'self',
    text: 'Stekni 12 štita. Izvuci 2 karte.',
    upgradedText: 'Stekni 16 štita. Izvuci 2 karte.',
    actions: [
      { kind: 'block', amount: 12 },
      { kind: 'draw', amount: 2 },
    ],
    upgradedActions: [
      { kind: 'block', amount: 16 },
      { kind: 'draw', amount: 2 },
    ],
  }),
  C({
    id: 'iznenadni_skok',
    name: 'Iznenadni skok',
    type: 'napad',
    rarity: 'cesta',
    cls: 'vukodlak',
    cost: 1,
    target: 'enemy',
    text: 'Nanesi 8 štete. Ako imaš štit, nanesi još 4.',
    upgradedText: 'Nanesi 11 štete. Ako imaš štit, nanesi još 5.',
    actions: [],
    onPlay: ({ api, state, targetIndex, upgraded }) => {
      let dmg = upgraded ? 11 : 8;
      if (state.player.block > 0) dmg += upgraded ? 5 : 4;
      api.attack(dmg, targetIndex);
    },
  }),
  C({
    id: 'grebanje',
    name: 'Grebanje',
    type: 'napad',
    rarity: 'cesta',
    cls: 'vukodlak',
    cost: 1,
    target: 'enemy',
    text: 'Nanesi 3 štete triput.',
    upgradedText: 'Nanesi 4 štete triput.',
    actions: [{ kind: 'damage', amount: 3, hits: 3 }],
    upgradedActions: [{ kind: 'damage', amount: 4, hits: 3 }],
  }),

  // --- uncommon ---
  C({
    id: 'krvavi_pir',
    name: 'Krvavi pir',
    type: 'moc',
    rarity: 'neobicna',
    cls: 'vukodlak',
    cost: 2,
    target: 'self',
    text: 'Na početku svakog poteza stekni 1 Snage.',
    upgradedText: 'Na početku svakog poteza stekni 1 Snage. (Košta 1)',
    actions: [{ kind: 'selfStatus', status: 'ritual', amount: 1 }],
    upgradedActions: [{ kind: 'selfStatus', status: 'ritual', amount: 1 }],
    keywords: ['Snaga'],
  }),
  C({
    id: 'zvjerska_snaga',
    name: 'Zvjerska snaga',
    type: 'moc',
    rarity: 'neobicna',
    cls: 'vukodlak',
    cost: 1,
    target: 'self',
    text: 'Stekni 2 Snage.',
    upgradedText: 'Stekni 3 Snage.',
    actions: [{ kind: 'selfStatus', status: 'strength', amount: 2 }],
    upgradedActions: [{ kind: 'selfStatus', status: 'strength', amount: 3 }],
  }),
  C({
    id: 'brutalnost',
    name: 'Brutalnost',
    type: 'vjestina',
    rarity: 'neobicna',
    cls: 'vukodlak',
    cost: 1,
    target: 'all-enemies',
    text: 'Nanesi svim neprijateljima štetu jednaku tvom Bijesu.',
    upgradedText: 'Nanesi svim neprijateljima štetu jednaku tvom Bijesu. Stekni 2 Bijesa.',
    actions: [],
    keywords: ['Pojačano bijesom'],
    onPlay: ({ api, state, upgraded }) => {
      api.attackAll(api.bjes());
      if (upgraded) api.applyStatus(state.player, 'player', 'bjes', 2);
    },
  }),
  C({
    id: 'preobrazaj',
    name: 'Preobražaj',
    type: 'vjestina',
    rarity: 'neobicna',
    cls: 'vukodlak',
    cost: 1,
    target: 'self',
    text: 'Stekni 4 Bijesa i 1 Snagu.',
    upgradedText: 'Stekni 5 Bijesa i 2 Snage.',
    actions: [
      { kind: 'gainBjes', amount: 4 },
      { kind: 'selfStatus', status: 'strength', amount: 1 },
    ],
    upgradedActions: [
      { kind: 'gainBjes', amount: 5 },
      { kind: 'selfStatus', status: 'strength', amount: 2 },
    ],
  }),
  C({
    id: 'krvava_zetva',
    name: 'Krvava žetva',
    type: 'napad',
    rarity: 'neobicna',
    cls: 'vukodlak',
    cost: 2,
    target: 'enemy',
    text: 'Nanesi 8 štete dvaput. Izliječi 3 zdravlja.',
    upgradedText: 'Nanesi 10 štete dvaput. Izliječi 5 zdravlja.',
    actions: [
      { kind: 'damage', amount: 8, hits: 2 },
      { kind: 'heal', amount: 3 },
    ],
    upgradedActions: [
      { kind: 'damage', amount: 10, hits: 2 },
      { kind: 'heal', amount: 5 },
    ],
  }),
  C({
    id: 'neman',
    name: 'Neman',
    type: 'napad',
    rarity: 'neobicna',
    cls: 'vukodlak',
    cost: 2,
    target: 'enemy',
    text: 'Nanesi 12 štete. Stekni 2 Bijesa.',
    upgradedText: 'Nanesi 16 štete. Stekni 3 Bijesa.',
    actions: [
      { kind: 'damage', amount: 12 },
      { kind: 'gainBjes', amount: 2 },
    ],
    upgradedActions: [
      { kind: 'damage', amount: 16 },
      { kind: 'gainBjes', amount: 3 },
    ],
  }),
  C({
    id: 'probadanje',
    name: 'Probadanje',
    type: 'napad',
    rarity: 'neobicna',
    cls: 'vukodlak',
    cost: 0,
    target: 'enemy',
    text: 'Nanesi 5 štete. Izvuci 1 kartu. Iscrpi.',
    upgradedText: 'Nanesi 8 štete. Izvuci 1 kartu. Iscrpi.',
    actions: [
      { kind: 'damage', amount: 5 },
      { kind: 'draw', amount: 1 },
    ],
    upgradedActions: [
      { kind: 'damage', amount: 8 },
      { kind: 'draw', amount: 1 },
    ],
    exhaust: true,
    keywords: ['Iscrpi'],
  }),

  // --- rare ---
  C({
    id: 'vukodlacki_bijes',
    name: 'Vukodlački bijes',
    type: 'napad',
    rarity: 'rijetka',
    cls: 'vukodlak',
    cost: 2,
    target: 'all-enemies',
    text: 'Potroši sav Bijes. Nanesi toliko štete svim neprijateljima. Izliječi pola toga.',
    upgradedText: 'Potroši sav Bijes. Nanesi toliko štete svim neprijateljima. Izliječi toliko.',
    actions: [],
    keywords: ['Pojačano bijesom'],
    onPlay: ({ api, state, upgraded }) => {
      const b = api.bjes();
      api.attackAll(b);
      delete state.player.statuses.bjes;
      const heal = upgraded ? b : Math.floor(b / 2);
      if (heal > 0) api.heal(state.player, 'player', heal);
    },
  }),
  C({
    id: 'krvavi_mjesec',
    name: 'Krvavi mjesec',
    type: 'moc',
    rarity: 'rijetka',
    cls: 'vukodlak',
    cost: 2,
    target: 'self',
    text: 'Na početku svakog poteza stekni 2 Snage.',
    upgradedText: 'Na početku svakog poteza stekni 2 Snage. (Košta 1)',
    actions: [{ kind: 'selfStatus', status: 'ritual', amount: 2 }],
    upgradedActions: [{ kind: 'selfStatus', status: 'ritual', amount: 2 }],
  }),
  C({
    id: 'zvjerski_gnjev',
    name: 'Zvjerski gnjev',
    type: 'napad',
    rarity: 'rijetka',
    cls: 'vukodlak',
    cost: -1,
    target: 'enemy',
    text: 'Iskoristi svu energiju. Nanesi (5 + Bijes) štete za svaku potrošenu energiju.',
    upgradedText: 'Iskoristi svu energiju. Nanesi (7 + Bijes) štete za svaku potrošenu energiju.',
    actions: [],
    keywords: ['Pojačano bijesom', 'X'],
    onPlay: ({ api, targetIndex, energySpent, upgraded }) => {
      const per = (upgraded ? 7 : 5) + api.bjes();
      api.attack(per, targetIndex, Math.max(0, energySpent));
    },
  }),
  C({
    id: 'mesarenje',
    name: 'Mesarenje',
    type: 'napad',
    rarity: 'rijetka',
    cls: 'vukodlak',
    cost: 3,
    target: 'enemy',
    text: 'Nanesi 9 štete triput.',
    upgradedText: 'Nanesi 12 štete triput.',
    actions: [{ kind: 'damage', amount: 9, hits: 3 }],
    upgradedActions: [{ kind: 'damage', amount: 12, hits: 3 }],
  }),
  C({
    id: 'pradavni_vuk',
    name: 'Pradavni vuk',
    type: 'moc',
    rarity: 'rijetka',
    cls: 'vukodlak',
    cost: 2,
    target: 'self',
    text: 'Stekni 3 Snage i 3 Bijesa.',
    upgradedText: 'Stekni 4 Snage i 4 Bijesa.',
    actions: [
      { kind: 'selfStatus', status: 'strength', amount: 3 },
      { kind: 'gainBjes', amount: 3 },
    ],
    upgradedActions: [
      { kind: 'selfStatus', status: 'strength', amount: 4 },
      { kind: 'gainBjes', amount: 4 },
    ],
  }),
  C({
    id: 'neukrotivost',
    name: 'Neukrotivost',
    type: 'vjestina',
    rarity: 'rijetka',
    cls: 'vukodlak',
    cost: 1,
    target: 'self',
    text: 'Stekni 10 štita i 3 Trnja.',
    upgradedText: 'Stekni 13 štita i 4 Trnja.',
    actions: [
      { kind: 'block', amount: 10 },
      { kind: 'selfStatus', status: 'thorns', amount: 3 },
    ],
    upgradedActions: [
      { kind: 'block', amount: 13 },
      { kind: 'selfStatus', status: 'thorns', amount: 4 },
    ],
    keywords: ['Trnje'],
  }),
];

// ============================================================
// VJEŠTICA — poison & hex control
// ============================================================
const VJESTICA: CardDef[] = [
  C({
    id: 'v_ubod',
    name: 'Ubod iglom',
    type: 'napad',
    rarity: 'osnovna',
    cls: 'vjestica',
    cost: 1,
    target: 'enemy',
    text: 'Nanesi 6 štete.',
    upgradedText: 'Nanesi 9 štete.',
    actions: [{ kind: 'damage', amount: 6 }],
    upgradedActions: [{ kind: 'damage', amount: 9 }],
  }),
  C({
    id: 'v_veo',
    name: 'Veo magle',
    type: 'vjestina',
    rarity: 'osnovna',
    cls: 'vjestica',
    cost: 1,
    target: 'self',
    text: 'Stekni 5 štita.',
    upgradedText: 'Stekni 8 štita.',
    actions: [{ kind: 'block', amount: 5 }],
    upgradedActions: [{ kind: 'block', amount: 8 }],
  }),
  C({
    id: 'v_uros',
    name: 'Urok trovanja',
    type: 'vjestina',
    rarity: 'osnovna',
    cls: 'vjestica',
    cost: 1,
    target: 'enemy',
    text: 'Daj 6 Otrova.',
    upgradedText: 'Daj 9 Otrova.',
    actions: [{ kind: 'status', status: 'poison', amount: 6 }],
    upgradedActions: [{ kind: 'status', status: 'poison', amount: 9 }],
    keywords: ['Otrov'],
  }),
  C({
    id: 'v_napoj',
    name: 'Mračni napoj',
    type: 'vjestina',
    rarity: 'cesta',
    cls: 'vjestica',
    cost: 1,
    target: 'enemy',
    text: 'Daj 3 Otrova i 1 Nemoć.',
    upgradedText: 'Daj 5 Otrova i 2 Nemoći.',
    actions: [
      { kind: 'status', status: 'poison', amount: 3 },
      { kind: 'status', status: 'weak', amount: 1 },
    ],
    upgradedActions: [
      { kind: 'status', status: 'poison', amount: 5 },
      { kind: 'status', status: 'weak', amount: 2 },
    ],
  }),
  C({
    id: 'v_zagasi',
    name: 'Ugarak',
    type: 'napad',
    rarity: 'cesta',
    cls: 'vjestica',
    cost: 1,
    target: 'enemy',
    text: 'Nanesi 7 štete.',
    upgradedText: 'Nanesi 10 štete.',
    actions: [{ kind: 'damage', amount: 7 }],
    upgradedActions: [{ kind: 'damage', amount: 10 }],
  }),
  C({
    id: 'v_isparenja',
    name: 'Isparenja',
    type: 'vjestina',
    rarity: 'cesta',
    cls: 'vjestica',
    cost: 1,
    target: 'all-enemies',
    text: 'Svim neprijateljima daj 3 Otrova.',
    upgradedText: 'Svim neprijateljima daj 4 Otrova.',
    actions: [{ kind: 'statusAll', status: 'poison', amount: 3 }],
    upgradedActions: [{ kind: 'statusAll', status: 'poison', amount: 4 }],
  }),
  C({
    id: 'v_uzdah',
    name: 'Uzdah vjetra',
    type: 'vjestina',
    rarity: 'cesta',
    cls: 'vjestica',
    cost: 1,
    target: 'self',
    text: 'Stekni 8 štita.',
    upgradedText: 'Stekni 11 štita.',
    actions: [{ kind: 'block', amount: 8 }],
    upgradedActions: [{ kind: 'block', amount: 11 }],
  }),
  C({
    id: 'v_crna_macka',
    name: 'Crna mačka',
    type: 'napad',
    rarity: 'cesta',
    cls: 'vjestica',
    cost: 1,
    target: 'enemy',
    text: 'Nanesi 5 štete. Daj 2 Ranjivosti.',
    upgradedText: 'Nanesi 7 štete. Daj 3 Ranjivosti.',
    actions: [
      { kind: 'damage', amount: 5 },
      { kind: 'status', status: 'vulnerable', amount: 2 },
    ],
    upgradedActions: [
      { kind: 'damage', amount: 7 },
      { kind: 'status', status: 'vulnerable', amount: 3 },
    ],
  }),
  C({
    id: 'v_zaziv',
    name: 'Zaziv duhova',
    type: 'vjestina',
    rarity: 'cesta',
    cls: 'vjestica',
    cost: 1,
    target: 'self',
    text: 'Izvuci 2 karte.',
    upgradedText: 'Izvuci 3 karte.',
    actions: [{ kind: 'draw', amount: 2 }],
    upgradedActions: [{ kind: 'draw', amount: 3 }],
  }),
  C({
    id: 'v_otrovni_dah',
    name: 'Otrovni dah',
    type: 'napad',
    rarity: 'cesta',
    cls: 'vjestica',
    cost: 1,
    target: 'enemy',
    text: 'Nanesi 4 štete. Daj 2 Otrova.',
    upgradedText: 'Nanesi 6 štete. Daj 3 Otrova.',
    actions: [
      { kind: 'damage', amount: 4 },
      { kind: 'status', status: 'poison', amount: 2 },
    ],
    upgradedActions: [
      { kind: 'damage', amount: 6 },
      { kind: 'status', status: 'poison', amount: 3 },
    ],
  }),
  C({
    id: 'v_uvenuce',
    name: 'Uvenuće',
    type: 'napad',
    rarity: 'cesta',
    cls: 'vjestica',
    cost: 1,
    target: 'enemy',
    text: 'Nanesi 6 štete. Ako meta ima Otrov, nanesi još 4.',
    upgradedText: 'Nanesi 8 štete. Ako meta ima Otrov, nanesi još 6.',
    actions: [],
    onPlay: ({ api, state, targetIndex, upgraded }) => {
      const tgt =
        targetIndex !== null && state.enemies[targetIndex]?.hp > 0
          ? state.enemies[targetIndex]
          : state.enemies.find((e) => e.hp > 0) ?? null;
      let dmg = upgraded ? 8 : 6;
      if (tgt && (tgt.statuses.poison ?? 0) > 0) dmg += upgraded ? 6 : 4;
      api.attack(dmg, targetIndex);
    },
  }),
  C({
    id: 'v_gavran',
    name: 'Jato gavrana',
    type: 'napad',
    rarity: 'cesta',
    cls: 'vjestica',
    cost: 1,
    target: 'enemy',
    text: 'Nanesi 4 štete dvaput. Daj 2 Otrova.',
    upgradedText: 'Nanesi 5 štete dvaput. Daj 3 Otrova.',
    actions: [
      { kind: 'damage', amount: 4, hits: 2 },
      { kind: 'status', status: 'poison', amount: 2 },
    ],
    upgradedActions: [
      { kind: 'damage', amount: 5, hits: 2 },
      { kind: 'status', status: 'poison', amount: 3 },
    ],
  }),

  // uncommon
  C({
    id: 'v_katalizator',
    name: 'Katalizator',
    type: 'vjestina',
    rarity: 'neobicna',
    cls: 'vjestica',
    cost: 1,
    target: 'enemy',
    text: 'Udvostruči Otrov na meti. Iscrpi.',
    upgradedText: 'Utrostruči Otrov na meti. Iscrpi.',
    actions: [],
    exhaust: true,
    keywords: ['Otrov', 'Iscrpi'],
    onPlay: ({ api, state, targetIndex, upgraded }) => {
      const tgt =
        targetIndex !== null && state.enemies[targetIndex]?.hp > 0
          ? state.enemies[targetIndex]
          : state.enemies.find((e) => e.hp > 0) ?? null;
      if (!tgt) return;
      const cur = tgt.statuses.poison ?? 0;
      const extra = upgraded ? cur * 2 : cur;
      if (extra > 0) api.applyStatus(tgt, state.enemies.indexOf(tgt), 'poison', extra);
    },
  }),
  C({
    id: 'v_odjek',
    name: 'Odjek',
    type: 'vjestina',
    rarity: 'neobicna',
    cls: 'vjestica',
    cost: 1,
    target: 'self',
    text: 'Sljedeća odigrana karta igra se dvaput.',
    upgradedText: 'Sljedeće dvije odigrane karte igraju se dvaput.',
    actions: [{ kind: 'selfStatus', status: 'echo', amount: 1 }],
    upgradedActions: [{ kind: 'selfStatus', status: 'echo', amount: 2 }],
    keywords: ['Odjek'],
  }),
  C({
    id: 'v_mrak',
    name: 'Mrak',
    type: 'vjestina',
    rarity: 'neobicna',
    cls: 'vjestica',
    cost: 2,
    target: 'all-enemies',
    text: 'Svima daj 2 Nemoći i 2 Ranjivosti.',
    upgradedText: 'Svima daj 3 Nemoći i 3 Ranjivosti.',
    actions: [
      { kind: 'statusAll', status: 'weak', amount: 2 },
      { kind: 'statusAll', status: 'vulnerable', amount: 2 },
    ],
    upgradedActions: [
      { kind: 'statusAll', status: 'weak', amount: 3 },
      { kind: 'statusAll', status: 'vulnerable', amount: 3 },
    ],
  }),
  C({
    id: 'v_napitak',
    name: 'Napitak moći',
    type: 'moc',
    rarity: 'neobicna',
    cls: 'vjestica',
    cost: 1,
    target: 'self',
    text: 'Stekni 2 Spretnosti.',
    upgradedText: 'Stekni 3 Spretnosti.',
    actions: [{ kind: 'selfStatus', status: 'dexterity', amount: 2 }],
    upgradedActions: [{ kind: 'selfStatus', status: 'dexterity', amount: 3 }],
  }),
  C({
    id: 'v_so_pepeo',
    name: 'So i pepeo',
    type: 'vjestina',
    rarity: 'neobicna',
    cls: 'vjestica',
    cost: 1,
    target: 'all-enemies',
    text: 'Svima daj 2 Krhkosti.',
    upgradedText: 'Svima daj 3 Krhkosti.',
    actions: [{ kind: 'statusAll', status: 'frail', amount: 2 }],
    upgradedActions: [{ kind: 'statusAll', status: 'frail', amount: 3 }],
  }),

  // rare
  C({
    id: 'v_kuga',
    name: 'Kuga',
    type: 'vjestina',
    rarity: 'rijetka',
    cls: 'vjestica',
    cost: 2,
    target: 'all-enemies',
    text: 'Svim neprijateljima daj 8 Otrova. Iscrpi.',
    upgradedText: 'Svim neprijateljima daj 12 Otrova. Iscrpi.',
    actions: [{ kind: 'statusAll', status: 'poison', amount: 8 }],
    upgradedActions: [{ kind: 'statusAll', status: 'poison', amount: 12 }],
    exhaust: true,
  }),
  C({
    id: 'v_senka',
    name: 'Sjenovitost',
    type: 'vjestina',
    rarity: 'rijetka',
    cls: 'vjestica',
    cost: 2,
    target: 'self',
    text: 'Stekni 1 Sjenovitost (sva primljena šteta postaje 1 na 1 potez). Iscrpi.',
    upgradedText: 'Stekni 1 Sjenovitost. Iscrpi. (Košta 1)',
    actions: [{ kind: 'selfStatus', status: 'intangible', amount: 1 }],
    upgradedActions: [{ kind: 'selfStatus', status: 'intangible', amount: 1 }],
    exhaust: true,
    keywords: ['Sjenovit'],
  }),
  C({
    id: 'v_morina_kletva',
    name: 'Morina kletva',
    type: 'moc',
    rarity: 'rijetka',
    cls: 'vjestica',
    cost: 2,
    target: 'self',
    text: 'Na početku svakog poteza svim neprijateljima daj 1 Otrov.',
    upgradedText: 'Na početku svakog poteza svim neprijateljima daj 2 Otrova.',
    actions: [{ kind: 'selfStatus', status: 'kletva', amount: 1 }],
    upgradedActions: [{ kind: 'selfStatus', status: 'kletva', amount: 2 }],
    keywords: ['Otrov'],
  }),
];

// ============================================================
// NEUTRAL — shared, found across classes
// ============================================================
const NEUTRAL: CardDef[] = [
  C({
    id: 'n_udar',
    name: 'Tup udar',
    type: 'napad',
    rarity: 'neobicna',
    cls: 'neutral',
    cost: 1,
    target: 'enemy',
    text: 'Nanesi 8 štete. Iscrpi.',
    upgradedText: 'Nanesi 11 štete. Iscrpi.',
    actions: [{ kind: 'damage', amount: 8 }],
    upgradedActions: [{ kind: 'damage', amount: 11 }],
    exhaust: true,
  }),
  C({
    id: 'n_okrjepa',
    name: 'Okrepa',
    type: 'vjestina',
    rarity: 'neobicna',
    cls: 'neutral',
    cost: 0,
    target: 'self',
    text: 'Izliječi 5 zdravlja. Iscrpi.',
    upgradedText: 'Izliječi 8 zdravlja. Iscrpi.',
    actions: [{ kind: 'heal', amount: 5 }],
    upgradedActions: [{ kind: 'heal', amount: 8 }],
    exhaust: true,
  }),
  C({
    id: 'n_oprez',
    name: 'Oprez',
    type: 'vjestina',
    rarity: 'cesta',
    cls: 'neutral',
    cost: 1,
    target: 'self',
    text: 'Stekni 5 štita. Stekni 1 Spretnost.',
    upgradedText: 'Stekni 7 štita. Stekni 1 Spretnost.',
    actions: [
      { kind: 'block', amount: 5 },
      { kind: 'selfStatus', status: 'dexterity', amount: 1 },
    ],
    upgradedActions: [
      { kind: 'block', amount: 7 },
      { kind: 'selfStatus', status: 'dexterity', amount: 1 },
    ],
  }),
  C({
    id: 'n_zamor',
    name: 'Iscrpljujući udarac',
    type: 'napad',
    rarity: 'cesta',
    cls: 'neutral',
    cost: 1,
    target: 'enemy',
    text: 'Nanesi 6 štete. Daj 1 Nemoć.',
    upgradedText: 'Nanesi 8 štete. Daj 2 Nemoći.',
    actions: [
      { kind: 'damage', amount: 6 },
      { kind: 'status', status: 'weak', amount: 1 },
    ],
    upgradedActions: [
      { kind: 'damage', amount: 8 },
      { kind: 'status', status: 'weak', amount: 2 },
    ],
  }),
];

// ============================================================
// STATUS & CURSE — junk added to your deck by enemies/events
// ============================================================
const STATUS: CardDef[] = [
  C({
    id: 'rana',
    name: 'Rana',
    type: 'stanje',
    rarity: 'posebna',
    cls: 'status',
    cost: -2,
    target: 'none',
    text: 'Nije moguće odigrati.',
    actions: [],
    flavor: 'Boli pri svakom pokretu.',
  }),
  C({
    id: 'opekotina',
    name: 'Opekotina',
    type: 'stanje',
    rarity: 'posebna',
    cls: 'status',
    cost: -2,
    target: 'none',
    text: 'Nije moguće odigrati. Na kraju poteza gubiš 2 zdravlja ako je u ruci.',
    upgradedText: 'Nije moguće odigrati. Na kraju poteza gubiš 4 zdravlja ako je u ruci.',
    actions: [],
  }),
  C({
    id: 'kletva_jad',
    name: 'Jad',
    type: 'kletva',
    rarity: 'posebna',
    cls: 'status',
    cost: -2,
    target: 'none',
    text: 'Nije moguće odigrati. Mrtav teret u špilu.',
    actions: [],
    flavor: 'Tuga koja se ne da odbaciti.',
  }),
  C({
    id: 'kletva_klin',
    name: 'Klin u srcu',
    type: 'kletva',
    rarity: 'posebna',
    cls: 'status',
    cost: -2,
    target: 'none',
    ethereal: true,
    text: 'Nije moguće odigrati. Nestaje na kraju poteza.',
    actions: [],
  }),
];

export const CARDS: CardDef[] = [...VUKODLAK, ...VJESTICA, ...NEUTRAL, ...STATUS];

export const STARTER_DECKS: Record<string, { id: string; count: number }[]> = {
  vukodlak: [
    { id: 'ugriz', count: 5 },
    { id: 'krzno', count: 4 },
    { id: 'razjari', count: 1 },
  ],
  vjestica: [
    { id: 'v_ubod', count: 5 },
    { id: 'v_veo', count: 4 },
    { id: 'v_uros', count: 1 },
  ],
};
